# Generated by Django 3.2.18 on 2023-05-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Princ', models.CharField(max_length=20)),
                ('loc', models.CharField(max_length=15)),
            ],
        ),
    ]
